name: timetrackingintegration

description: Integration between Jira and Toggl with pomodoro
publish_to: none
version: 1.5.4+8

dependencies:
  flutter:
    sdk: flutter
  background_fetch: ^0.7.2
  cupertino_icons: ^1.0.3
  http: ^0.13.3
  path_provider: ^2.0.2
  shared_preferences: ^2.0.6
  rxdart: ^0.27.1
  countdown_flutter: ^0.1.1
  flutter_ringtone_player: ^3.0.0
  wakelock: ^0.5.2
  flutter_local_notifications: ^5.0.0+4
  package_info: ^2.0.2
  flutter_dnd: ^0.1.2
  flutter_slidable: ^0.6.0
  modal_bottom_sheet: ^2.0.0
  settings_ui: ^1.0.0
  sqflite: ^2.0.0+3
  flutter_tagging: ^3.0.0
  flutter_datetime_picker: ^1.4.0
  pull_to_refresh: ^2.0.0
  flutter_svg: ^0.22.0
  mime: ^1.0.0
dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  e2e: ^0.7.0+1
  pedantic: ^1.8.0
  flutter_spinkit: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - icons/

environment:
  sdk: ">=2.3.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"
