name: timetrackingintegration

description: Integration between Jira and Toggl with pomodoro
publish_to: none
version: 1.5.4+8

dependencies:
  flutter:
    sdk: flutter
  background_fetch: ^0.5.5
  cupertino_icons: ^0.1.3
  http: ^0.12.0+4
  path_provider: ^1.6.1
  shared_preferences: ^0.5.6+2
  rxdart: ^0.23.1
  countdown_flutter: ^0.1.1
  flutter_ringtone_player: ^2.0.0
  wakelock: ^0.1.4+1
  flutter_local_notifications: ^1.4.1
  package_info: ^0.4.0+16
  flutter_dnd: ^0.1.2
  flutter_slidable: ^0.5.4
  modal_bottom_sheet: ^0.1.5
  settings_ui: ^0.2.0
  sqflite: ^1.3.0
  flutter_tagging: ^2.2.0+3
  flutter_datetime_picker: ^1.4.0
  pull_to_refresh: ^1.6.1
  flutter_svg: ^0.19.0
  mime: ^0.9.7
dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  e2e: ^0.2.4+2
  pedantic: ^1.8.0
  flutter_spinkit: ^4.1.2

flutter:
  uses-material-design: true
  assets:
    - icons/

environment:
  sdk: ">=2.3.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"
